# Generated by Django 3.1.3 on 2020-12-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
